// Only the public publishable key is used. Authorization is checked by every RPC.
export class OpsAPI {
 constructor(config,{fetcher=(...args)=>fetch(...args),storage=sessionStorage,now=()=>Date.now()}={}){this.config=config;this.fetcher=fetcher;this.storage=storage;this.now=now;this.session=null;this.refreshing=null;this.epoch=0;try{this.session=JSON.parse(storage.getItem('tb-ops-session')||'null')}catch{storage.removeItem('tb-ops-session')}}
 clear(){this.epoch++;this.session=null;this.storage.removeItem('tb-ops-session')}
 remember(data,epoch=this.epoch){if(epoch!==this.epoch)throw Error('SESSION_CHANGED');this.session={access_token:data.access_token,refresh_token:data.refresh_token,expires_at:data.expires_at||Math.floor(this.now()/1000)+data.expires_in};this.storage.setItem('tb-ops-session',JSON.stringify(this.session))}
 async request(path,body,token){const r=await this.fetcher(this.config.url+path,{method:'POST',headers:{apikey:this.config.key,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});let data;try{data=await r.json()}catch{data={}}if(!r.ok){const e=Error(data.message||data.error_description||data.msg||'REQUEST_FAILED');e.status=r.status;throw e}return data}
 send(email){return this.request('/auth/v1/otp',{email,create_user:false})}
 async signIn(email,password){const epoch=this.epoch;const data=await this.request('/auth/v1/token?grant_type=password',{email,password});this.remember(data,epoch);try{return await this.rpc('me')}catch(e){await this.logout();throw e}}
 async verify(email,token){const epoch=this.epoch;const data=await this.request('/auth/v1/verify',{email,token,type:'email'});this.remember(data,epoch);try{return await this.rpc('me')}catch(e){await this.logout();throw e}}
 async refresh(){if(this.refreshing)return this.refreshing;if(!this.session)throw Error('LOGIN_REQUIRED');const token=this.session.refresh_token,epoch=this.epoch;this.refreshing=this.request('/auth/v1/token?grant_type=refresh_token',{refresh_token:token}).then(data=>this.remember(data,epoch)).catch(e=>{if(e.status===400||e.status===401)this.clear();throw e}).finally(()=>this.refreshing=null);return this.refreshing}
 async rpc(section,args={}){if(!this.session)throw Error('LOGIN_REQUIRED');const epoch=this.epoch;try{if((this.session.expires_at*1000)-this.now()<60000)await this.refresh();let data;try{data=await this.request((section==='health'?'/rest/v1/rpc/godot_ops_health':'/rest/v1/rpc/godot_ops_read'),(section==='health'?{}:{p_section:section,...args}),this.session.access_token)}catch(e){if(e.status!==401)throw e;await this.refresh();data=await this.request((section==='health'?'/rest/v1/rpc/godot_ops_health':'/rest/v1/rpc/godot_ops_read'),(section==='health'?{}:{p_section:section,...args}),this.session.access_token)}if(epoch!==this.epoch)throw Error('SESSION_CHANGED');return data}catch(e){if(epoch===this.epoch&&(e.status===401||e.status===403||/ADMIN_REQUIRED|ADMIN_SESSION_EXPIRED/.test(e.message)))this.clear();throw e}}
 async logout(){const token=this.session?.access_token;this.clear();if(token){try{await this.request('/auth/v1/logout?scope=local',{},token)}catch{/* Local data is already cleared even if network logout failed. */}}}
}
